version: '3'

services:
   spark:
     build: ./data
     ports:
       - "8088:8088"
       - "8042:8042"
       - "4040:4040"
     entrypoint:
       - "/etc/bootstrap.sh"
       - -d
     container_name: some-spark
     depends_on:
       - src-mysql
       - dst-mysql

   src-mysql:
     image: mysql
     container_name: src-mysql
     environment:
      - MYSQL_ROOT_PASSWORD=password

   dst-mysql:
     image: mysql
     container_name: dst-mysql
     environment:
      - MYSQL_ROOT_PASSWORD=password
